/**
 * Nature's Beauty Construction — Design Tokens (JS mirror of tokens.css)
 * All values reference CSS custom properties so they stay in sync with the stylesheet.
 */

export const tokens = {
  color: {
    // Brand gold
    gold100: 'var(--gold-100)',
    gold200: 'var(--gold-200)',
    gold300: 'var(--gold-300)',
    gold400: 'var(--gold-400)',
    gold500: 'var(--gold-500)',
    gold600: 'var(--gold-600)',
    gold700: 'var(--gold-700)',
    gold800: 'var(--gold-800)',
    gold900: 'var(--gold-900)',
    // Forest green
    green100: 'var(--green-100)',
    green200: 'var(--green-200)',
    green300: 'var(--green-300)',
    green400: 'var(--green-400)',
    green500: 'var(--green-500)',
    green600: 'var(--green-600)',
    green700: 'var(--green-700)',
    green800: 'var(--green-800)',
    green900: 'var(--green-900)',
    // Earth brown
    brown100: 'var(--brown-100)',
    brown200: 'var(--brown-200)',
    brown300: 'var(--brown-300)',
    brown400: 'var(--brown-400)',
    brown500: 'var(--brown-500)',
    brown600: 'var(--brown-600)',
    brown700: 'var(--brown-700)',
    brown800: 'var(--brown-800)',
    brown900: 'var(--brown-900)',
    // Semantic
    primary: 'var(--color-primary)',
    primaryHover: 'var(--color-primary-hover)',
    primaryActive: 'var(--color-primary-active)',
    primarySubtle: 'var(--color-primary-subtle)',
    primaryOn: 'var(--color-primary-on)',
    secondary: 'var(--color-secondary)',
    secondaryHover: 'var(--color-secondary-hover)',
    secondaryActive: 'var(--color-secondary-active)',
    secondarySubtle: 'var(--color-secondary-subtle)',
    secondaryOn: 'var(--color-secondary-on)',
    surface: 'var(--color-surface)',
    surfaceRaised: 'var(--color-surface-raised)',
    surfaceSunken: 'var(--color-surface-sunken)',
    surfaceOverlay: 'var(--color-surface-overlay)',
    surfaceInverse: 'var(--color-surface-inverse)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textTertiary: 'var(--color-text-tertiary)',
    textDisabled: 'var(--color-text-disabled)',
    textInverse: 'var(--color-text-inverse)',
    textAccent: 'var(--color-text-accent)',
    textLink: 'var(--color-text-link)',
    textLinkHover: 'var(--color-text-link-hover)',
    border: 'var(--color-border)',
    borderStrong: 'var(--color-border-strong)',
    borderFocus: 'var(--color-border-focus)',
    success: 'var(--color-success)',
    successSubtle: 'var(--color-success-subtle)',
    warning: 'var(--color-warning)',
    warningSubtle: 'var(--color-warning-subtle)',
    error: 'var(--color-error)',
    errorSubtle: 'var(--color-error-subtle)',
    info: 'var(--color-info)',
    infoSubtle: 'var(--color-info-subtle)',
  },
  font: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
  },
  text: {
    '2xs': 'var(--text-2xs)',
    xs: 'var(--text-xs)',
    sm: 'var(--text-sm)',
    base: 'var(--text-base)',
    lg: 'var(--text-lg)',
    xl: 'var(--text-xl)',
    '2xl': 'var(--text-2xl)',
    '3xl': 'var(--text-3xl)',
    '4xl': 'var(--text-4xl)',
    '5xl': 'var(--text-5xl)',
    '6xl': 'var(--text-6xl)',
    '7xl': 'var(--text-7xl)',
  },
  space: {
    0: 'var(--space-0)',
    px: 'var(--space-px)',
    '0.5': 'var(--space-0-5)',
    1: 'var(--space-1)',
    1.5: 'var(--space-1-5)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
    10: 'var(--space-10)',
    12: 'var(--space-12)',
    16: 'var(--space-16)',
    20: 'var(--space-20)',
    24: 'var(--space-24)',
    32: 'var(--space-32)',
  },
  radius: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    '3xl': 'var(--radius-3xl)',
    full: 'var(--radius-full)',
  },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
    inner: 'var(--shadow-inner)',
    gold: 'var(--shadow-gold)',
    green: 'var(--shadow-green)',
  },
  transition: {
    fast: 'var(--transition-fast)',
    base: 'var(--transition-base)',
    slow: 'var(--transition-slow)',
  },
} as const;

export type Tokens = typeof tokens;
